#%RAML 1.0 NamedExample
  ClaimNumber: NRM171034809
  ClaimantID: ABCDE
  SystemEndpoint: http://pv-diclaims.auiag.corp:10080/cc/ws/di/cc/webservices/claimInquiry/claimValidation/IClaimValidationAPI
  ClaimNumberExists: true
  SourceSystem: GCC